# Generated by Django 5.2.7 on 2026-04-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.AddField(
            model_name='department',
            name='established_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='department',
            name='is_nba_accredited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
